### ISSUE TITLE
Audio keeps playing after player is destroyed

### ISSUE THREAD

**Issue by voslartomas** [bambuser/react-native-bambuser-player#16]
We are using SwiperFlatList to switch between videos, on of them is bambuser player and there is a problem when we switch to other player, because bambuser player is destroyed (there is no reference to video player), but audio keeps playing. Any idea why?

**Comment by peterlofquist** [comment]
Thanks for your issue report! I'd suggest that you make sure to call `stop()` on the player instance before throwing away the player, if you're not doing that already.

I'll make a note to myself to call `stop()` inside of this component when the view is unmounted to avoid this inconvience.

**Comment by voslartomas** [comment]
@peterlofquist Hello, thank you for suggestion, unfortunately we are not able to do that as we are using swiper, which has no listener on such event, so we would need to hack the solution (we are hacking right now), but for instance react-native-video is working just fine, so I guess they are stopping on unmount as well. So we would be grateful if you can do this in this lib as well. Thanks a lot

**Comment by voslartomas** [comment]
@peterlofquist Hello any chance of this being fixed?

**Comment by peterlofquist** [comment]
@voslartomas in the new version 0.0.17 the component will no call `.stop()` when being unmounted. When I tried it together with `SwiperFlatList` I still needed to call the `.stop()` function on the component when the player left the current presented index in `SwiperFlatList` because the player was still in the render tree, but perhaps your setup is slightly different than mine and this still solves your problem. :-)

This issue:
> bambuser player is destroyed (there is no reference to video player), but audio keeps playing.

is however handled and I close this issue. If you find any more issues regarding this please re-open.

**Comment by voslartomas** [comment]
Will try it out, thanks a lot!

**Comment by voslartomas** [comment]
@peterlofquist It fixed all our problems, thanks again.
