### ISSUE TITLE
onCurrentViewerUpdate

### ISSUE THREAD

**Issue by seung1231** [bambuser/react-native-bambuser-player#4]
1. If I am a user watching the stream, does the function onCurrentViewerUpdate not count myself? Do I have to start with 1 on the player side? 

2. I have both onCurrentViewerUpdate function and onTotalViewerUpdate function running on render, but to separate variables. But the onCurrentViewerUpdate function is not returning any values. Is this a common problem?

**Comment by seung1231** [comment]
I have both onCurrentViewerUpdate function and onTotalViewerUpdate function running but to separate variables.

**Comment by peterlofquist** [comment]
Thanks for the report!

There was indeed a problem where onCurrentViewerCountUpdate callback was never called. It's now fixed in the latest version `0.0.12`.

And to answer your questions for clarity:
1) The onCurrentViewerUpdate does count yourself. If you are viewing the stream alone the onCurrentViewerUpdate should give you the viewer count of 1. (After upgrading to `react-native-bambuser-player 0.0.12`)

2) There was indeed a problem with the onCurrentViewerUpdate callback. It's now fixed in `react-native-bambuser-player 0.0.12`.

Please let me know if upgrading to latest version solves your issue! 🙂
