### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by seung1231** [bambuser/react-native-bambuser-player#6]
I have noticed a startTimer and stopTimer function in the API? Is there a timer function for broadcaster and player that shows timer that are in sync?

**Comment by peterlofquist** [comment]
There is a `startTimer` & `stopTimer` function in the native player component to trigger the `onProgressUpdate(liveState, currentPosition, totalDuration)` callback at controlled intervals, which helps you present the correct values for your users.

The broadcast component does not have this kind of callback, which means you have to implement your own timer to indicate how long you have been broadcasting for.

To answer your question regarding a timer which is synced between the broadcaster and player the answer is no, there's no such thing, and it does not really make any sense to have a timer which is synced between these two components due to the nature of the live video pipeline. The video you play in the video component have a slight delay(latency) when playing because the data have to be sent from one point to another via some additional steps along the way when traveling over the internet.

I hope this answers your question. I'm closing this issue, feel free to reopen if I misinterpreted the question or if you have any follow up questions. Thanks!
